### PR TITLE
Make shell scripts executable

### PR DESCRIPTION
**Pull request by yrodiere**
Creating a PR for this because *maybe* there was a reason for those files not to be executable?

### CODE REVIEW

**Comment by gsmet** [comment]
They are called on CI with a specific option to stop on the first error and make the job fail because of that. That's why I didn't make them executable when I generalize the release process (they weren't before so I kept it that way).

If we want to make them executable (and we want to use this particularity in the Jenkins job), we should include the option in the shebang.

And we should test that the Jenkins job is still stopped at the first failure.

Not sure it's worth it tbh :).

**Comment by yrodiere** [comment]
Ok... It's just that it's a bit of a pain to test: you have to chmod before your tests, but remember to un-chmod before you commit.
But I guess I won't have to work a lot on these scripts anyway.

**Comment by gsmet** [comment]
Just use /bin/bash thescript.sh .

**Comment by DavideD** [comment]
Couldn't  you run them using sh?

**Comment by yrodiere** [comment]
I guess I can. Closing :)

**Pull request closed without merging**
