### PR TITLE
Exclude adding components in changelog for hibernate search

### PR DESCRIPTION
**Pull request by DavideD**
@Sanne this should exclude the compoents in the changelog for search

### CODE REVIEW

**Comment by Sanne** [comment]
thanks!

**Comment by gsmet** [comment]
Is there any good reason we make an exception for Search on this?

I think we should try to be consistent between our projects. Either use the components or not for all of them. I don't have a strong opinion about this, just that I would prefer us being consistent, either way or the other.

@gunnarmorling WDYT for Validator?

**Comment by Sanne** [comment]
the "components" section isn't very useful for Search, and it was looking quite ugly.
It's very useful for OGM as often a dialog will be data-store specific, so I think it's fine to be different.

BTW they have been different so far..

**Comment by DavideD** [comment]
I think it's fine if we have some minor differences in the changelog of different projects.

In OGM I think people might be interested to know which backend has changed.

@Sanne wouldn't be useful for people to know which changes affect the different "backend" (elasticsearch, jms, jgroup, and so on )?

**Comment by Sanne** [comment]
The problem is that most issues in Search aren't as easily classified as in OGM, e.g. you might have multiple "backends" affected but more likely none.

Anyway the point is that Search never had this format, we're not switching format because a script knows better ;)

**Comment by gsmet** [comment]
OK, fair enough. Just wanted to be sure we really wanted that!

**Pull request merged**
